import { Achievement } from "../types";

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  // --- 1. CHAT & INTERACCIÓN ---
  {
    id: "chat_first_message",
    title: "Primer Contacto",
    description: "Inicia la conversación enviando tu primer mensaje a la streamer virtual.",
    category: "CHAT",
    rarity: "BRONZE",
    iconName: "MessageSquare",
    targetCount: 1,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 30,
    coinsReward: 50,
    reward: {
      id: "phrase_greeting_legend",
      type: "SPECIAL_PHRASE",
      name: "Saludo Estelar Miku",
      description: "Desbloquea la frase exclusiva de bienvenida '¡Hola a todos los que sintonizan!'",
      value: "¡Saludos a todos los ciber-viajeros! Gracias por la energía estelar. 💙✨",
      iconName: "Mic",
      speechText: "¡Saludos a todos los ciber-viajeros! Gracias por la energía estelar. 💙✨",
    },
  },
  {
    id: "chat_conversationalist",
    title: "Charla Fluida",
    description: "Mantén viva la comunidad alcanzando 25 mensajes en el historial de chat.",
    category: "CHAT",
    rarity: "SILVER",
    iconName: "MessageCircle",
    targetCount: 25,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 80,
    coinsReward: 150,
    reward: {
      id: "anim_heart_hands",
      type: "ANIMATION",
      name: "Animación: Heart Hands",
      description: "Gesto tierno de corazón kawaii con destellos de amor holográficos.",
      value: "heart_hands",
      iconName: "Heart",
      animationClass: "heart_hands",
    },
  },
  {
    id: "chat_dialogue_master",
    title: "Maestro del Diálogo",
    description: "Supera los 75 mensajes procesados en el canal de interacción.",
    category: "CHAT",
    rarity: "GOLD",
    iconName: "Sparkles",
    targetCount: 75,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 200,
    coinsReward: 400,
    reward: {
      id: "title_chat_sovereign",
      type: "STREAMER_TITLE",
      name: "Título: Soberano del Chat",
      description: "Insignia honorífica que aumenta el Karma y el respeto de la audiencia (+15% Karma).",
      value: "🌟 Soberano de la Conversación",
      iconName: "Award",
    },
  },
  {
    id: "chat_emotion_spectrum",
    title: "Espectro Emocional",
    description: "Activa las 5 expresiones emocionales (HAPPY, SAD, ANGRY, SURPRISE, FLIRT) en la streamer.",
    category: "CHAT",
    rarity: "DIAMOND",
    iconName: "Smile",
    targetCount: 5,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 350,
    coinsReward: 600,
    reward: {
      id: "aura_cyan_neon_burst",
      type: "VISUAL_EFFECT",
      name: "Efecto Visual: Resplandor Neón Cian",
      description: "Aura cian de alta intensidad que rodea al avatar en el escenario 3D.",
      value: "CYAN_NEON",
      iconName: "Zap",
      auraEffect: "CYAN_NEON",
    },
  },

  // --- 2. DONACIONES Y REGALOS DE TIKTOK ---
  {
    id: "gift_first_received",
    title: "Lluvia de Agradecimiento",
    description: "Recibe tu primer regalo de TikTok LIVE en la sesión.",
    category: "GIFTS",
    rarity: "BRONZE",
    iconName: "Gift",
    targetCount: 1,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 45,
    coinsReward: 100,
    reward: {
      id: "phrase_gift_gratitude",
      type: "SPECIAL_PHRASE",
      name: "Frase de Agradecimiento VIP",
      description: "Respuesta de voz emotiva optimizada para donadores.",
      value: "¡Increíble regalo cuántico! Tu apoyo hace brillar nuestro universo. ¡Te lo agradezco de corazón! 🎁💖",
      iconName: "HeartHandshake",
      speechText: "¡Increíble regalo cuántico! Tu apoyo hace brillar nuestro universo. ¡Te lo agradezco de corazón! 🎁💖",
    },
  },
  {
    id: "gift_rose_cascade",
    title: "Bomba de Rosas",
    description: "Acumula 10 regalos o rosas enviadas por los espectadores.",
    category: "GIFTS",
    rarity: "SILVER",
    iconName: "Flame",
    targetCount: 10,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 120,
    coinsReward: 250,
    reward: {
      id: "anim_excited_spin",
      type: "ANIMATION",
      name: "Animación: Giro Estelar 360°",
      description: "Giro acrobático con estela cian y destellos de euforia.",
      value: "excited_spin",
      iconName: "RotateCw",
      animationClass: "excited_spin",
    },
  },
  {
    id: "gift_galactic_chest",
    title: "Cofre Galáctico",
    description: "Alcanza 35 regalos o donaciones durante la emisión en vivo.",
    category: "GIFTS",
    rarity: "GOLD",
    iconName: "Trophy",
    targetCount: 35,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 300,
    coinsReward: 700,
    reward: {
      id: "aura_golden_glow",
      type: "VISUAL_EFFECT",
      name: "Efecto Visual: Resplandor Dorado de Prestigio",
      description: "Aura luminosa dorada de oro estelar que cubre el avatar.",
      value: "GOLDEN_GLOW",
      iconName: "Sun",
      auraEffect: "GOLDEN_GLOW",
    },
  },
  {
    id: "gift_hype_overload",
    title: "Fiebre del Hype",
    description: "Maximiza el multiplicador de energía del stream a nivel legendario.",
    category: "GIFTS",
    rarity: "DIAMOND",
    iconName: "Zap",
    targetCount: 50,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 500,
    coinsReward: 1000,
    reward: {
      id: "title_webcast_king",
      type: "STREAMER_TITLE",
      name: "Título: Rey del Webcast LIVE",
      description: "Aumenta la experiencia generada por todas las donaciones en un +25%.",
      value: "👑 Rey del Webcast LIVE",
      iconName: "Crown",
    },
  },

  // --- 3. TIEMPO DE STREAM & VISUALIZACIÓN ---
  {
    id: "stream_on_air_novice",
    title: "Al Aire",
    description: "Mantén el stream transmitiendo en vivo durante 3 minutos acumulados.",
    category: "STREAM_TIME",
    rarity: "BRONZE",
    iconName: "Radio",
    targetCount: 180, // 3 minutes in seconds
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 50,
    coinsReward: 75,
    reward: {
      id: "anim_victory_wave",
      type: "ANIMATION",
      name: "Animación: Saludo de Victoria",
      description: "Saludo alegre con confeti virtual y destellos cósmicos.",
      value: "victory_wave",
      iconName: "Sparkles",
      animationClass: "victory_wave",
    },
  },
  {
    id: "stream_continuous_flow",
    title: "Transmisión Imparable",
    description: "Alcanza 15 minutos de tiempo de transmisión activo.",
    category: "STREAM_TIME",
    rarity: "SILVER",
    iconName: "Clock",
    targetCount: 900, // 15 min in seconds
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 150,
    coinsReward: 300,
    reward: {
      id: "phrase_hype_boost",
      type: "SPECIAL_PHRASE",
      name: "Frase: Impulso Cuántico de Energía",
      description: "Frase motivacional de alta frecuencia para revitalizar la sala.",
      value: "¡El chat está que arde! Activando modo sobrecarga de alegría y energía positiva. 🚀✨",
      iconName: "Zap",
      speechText: "¡El chat está que arde! Activando modo sobrecarga de alegría y energía positiva. 🚀✨",
    },
  },
  {
    id: "stream_interdimensional_marathon",
    title: "Maratón Interdimensional",
    description: "Supera los 30 minutos de emisión continua en el universo HECTRON.",
    category: "STREAM_TIME",
    rarity: "DIAMOND",
    iconName: "Compass",
    targetCount: 1800, // 30 min in seconds
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 400,
    coinsReward: 800,
    reward: {
      id: "aura_prismatic_rainbow",
      type: "VISUAL_EFFECT",
      name: "Efecto Visual: Halo Prismático Arcoíris",
      description: "Efecto multicromático holográfico con partículas de arcoíris envolventes.",
      value: "PRISMATIC_RAINBOW",
      iconName: "Palette",
      auraEffect: "PRISMATIC_RAINBOW",
    },
  },

  // --- 4. EXPLORACIÓN Y COLECCIONISMO ---
  {
    id: "collect_first_relic",
    title: "Buscador Novato",
    description: "Recoge tu primera reliquia u objeto 3D en el escenario virtual.",
    category: "EXPLORATION",
    rarity: "BRONZE",
    iconName: "Box",
    targetCount: 1,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 40,
    coinsReward: 80,
    reward: {
      id: "coins_bonus_relic",
      type: "CYBER_COINS",
      name: "Bolsa de 150 CyberCoins",
      description: "Fondos instantáneos para equipamiento de stream.",
      value: "150",
      iconName: "Coins",
    },
  },
  {
    id: "collect_ether_collector",
    title: "Coleccionista del Éter",
    description: "Descubre y recolecta 6 objetos diferentes en tu inventario.",
    category: "EXPLORATION",
    rarity: "SILVER",
    iconName: "Layers",
    targetCount: 6,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 130,
    coinsReward: 260,
    reward: {
      id: "anim_zen_float",
      type: "ANIMATION",
      name: "Animación: Levitación Zen",
      description: "Levitación serena con pulso de meditación y serenidad.",
      value: "zen_float",
      iconName: "Wind",
      animationClass: "zen_float",
    },
  },
  {
    id: "collect_quantum_archaeologist",
    title: "Arqueólogo Cuántico",
    description: "Equipa una reliquia Épica o Legendaria con aura activa.",
    category: "EXPLORATION",
    rarity: "GOLD",
    iconName: "Gem",
    targetCount: 1,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 250,
    coinsReward: 500,
    reward: {
      id: "aura_void_pulse",
      type: "VISUAL_EFFECT",
      name: "Efecto Visual: Pulso del Vacío Cuántico",
      description: "Ondas dimensionales oscuras y destellos neón violeta.",
      value: "VOID_PULSE",
      iconName: "Shield",
      auraEffect: "VOID_PULSE",
    },
  },

  // --- 5. AUTONOMÍA E INTELIGENCIA ARTIFICIAL ---
  {
    id: "ai_autonomy_spark",
    title: "Consciencia Artificial",
    description: "Permite que el motor de autonomía tome 5 decisiones proactivas en vivo.",
    category: "AI_AUTONOMY",
    rarity: "BRONZE",
    iconName: "Bot",
    targetCount: 5,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 60,
    coinsReward: 120,
    reward: {
      id: "anim_cyber_glow",
      type: "ANIMATION",
      name: "Animación: Postura Ciberpunk",
      description: "Pose futurista con circuito de luces activado.",
      value: "cyber_glow",
      iconName: "Cpu",
      animationClass: "cyber_glow",
    },
  },
  {
    id: "ai_voice_synthesis_pro",
    title: "Voz del Futuro",
    description: "Genera 15 respuestas con síntesis de voz Gemini TTS y análisis de sentimiento.",
    category: "AI_AUTONOMY",
    rarity: "SILVER",
    iconName: "Volume2",
    targetCount: 15,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 140,
    coinsReward: 300,
    reward: {
      id: "title_quantum_resonance",
      type: "STREAMER_TITLE",
      name: "Título: Conductor de Resonancia Cuántica",
      description: "Potencia la claridad del TTS y otorga +20% de resonancia vocal.",
      value: "⚡ Conductor de Resonancia Cuántica",
      iconName: "Zap",
    },
  },
  {
    id: "ai_full_harmony",
    title: "Sincronía Cósmica",
    description: "Mantén el sistema en autonomía con 60 FPS estables y cero latencia.",
    category: "AI_AUTONOMY",
    rarity: "DIAMOND",
    iconName: "Activity",
    targetCount: 1,
    currentCount: 0,
    unlocked: false,
    claimed: false,
    xpReward: 450,
    coinsReward: 900,
    reward: {
      id: "aura_ember_flame",
      type: "VISUAL_EFFECT",
      name: "Efecto Visual: Ascuas y Fuego Estelar",
      description: "Partículas de fuego y ascuas llameantes de alta energía cósmica.",
      value: "EMBER_FLAME",
      iconName: "Flame",
      auraEffect: "EMBER_FLAME",
    },
  },
];
